sudo: required

# matrix layout based on:
# https://github.com/libressl-portable/portable/blob/9e090286b55def5ca2c0cc375c65023a70d8796e/.travis.yml

env:
  global:
    - RACKET_DIR=~/racket
    - IMPL=racket

matrix:
  include:
    - env: RACKET_VERSION=DOCKER # use default mode of mal repo
      services: docker
    - env: RACKET_VERSION=6.1    # same version than mal repo
    - env: RACKET_VERSION=7.5    # current version
    - env: RACKET_VERSION=HEAD
    - env: RACKET_VERSION=HEADCS
    - env: RACKET_VERSION=RELEASE
    - env: RACKET_VERSION=RELEASECS
install:
  - if [ $RACKET_VERSION != "DOCKER" ]; then export NO_DOCKER=1; fi

  - if [ -n "${NO_DOCKER}" ]; then git clone --depth 1 https://github.com/greghendershott/travis-racket.git; fi
  - if [ -n "${NO_DOCKER}" ]; then cat travis-racket/install-racket.sh | bash; fi # pipe to bash not sh!
  - if [ -n "${NO_DOCKER}" ]; then export PATH="${RACKET_DIR}/bin:${PATH}"; fi  #install-racket.sh can't set for us

  - if [ -n "${NO_DOCKER}" ]; then racket -v; else docker run -it -u $(id -u) -v `pwd`:/mal kanaka/mal-test-racket racket -v; fi

script:
  # Build, test, perf
  - ./.travis_test.sh build ${IMPL}
  - ./.travis_test.sh test ${IMPL}
  - STEP=stepA REGRESS=1 HARD=1 OPTIONAL=0 ./.travis_test.sh test ${IMPL}
  - ./.travis_test.sh perf ${IMPL}
